### ISSUE TITLE
Exception in line 84, in createListingSite

### ISSUE THREAD

**Issue by enishoca** [enishoca/openhab-kodi#2]
I get this on log:

20:36:31 T:1351611424  NOTICE: [openHab] Initializing - Main Menu
20:36:31 T:1351611424  NOTICE: [openHab] DEBUG: getJsonSiteMap url : [http://127.0.0.1:8080/rest/sitemaps/default/default?type=json]
20:36:31 T:1351611424  NOTICE: [openHab] DEBUG: getJson json_string : [{"id":"default","title":"Main Menu","link":"http://127.0.0.1:8080/rest/sitemaps/default/default","leaf":"true","
widget":[{"widgetId":"default_0","type":"Frame","label":"","icon":"frame","widget":[{"widgetId":"default_0_0","type":"Group","label":"Alarm","icon":"group","linkedPage":{"id":"0000","
title":"Alarm","icon":"group","link":"http://127.0.0.1:8080/rest/sitemaps/default/0000","leaf":"false"}},{"widgetId":"default_0_0_1","type":"Text","label":"Date [Sunday, 10.05.2015]",
"icon":"calendar","item":{"type":"DateTimeItem","name":"Date","state":"2015-05-10T20:24:27","link":"http://127.0.0.1:8080/rest/items/Date"}},{"widgetId":"default_0_0_1_2","type":"Swit
ch","label":"Rele 1 Timer (Ventilador)","icon":"light-off","item":{"type":"SwitchItem","name":"Rele1_Ocio_Timer","state":"OFF","link":"http://127.0.0.1:8080/rest/items/Rele1_Ocio_Time
r"}},{"widgetId":"default_0_0_1_2_3","type":"Switch","label":"Karla PC","icon":"switch-on","item":{"type":"SwitchItem","name":"KarlaPC","state":"ON","link":"http://127.0.0.1:8080/rest
/items/KarlaPC"}},{"widgetId":"default_0_0_1_2_3_4","type":"Switch","label":"Juan PC","icon":"switch-on","item":{"type":"SwitchItem","name":"JuanPC","state":"ON","link":"http://127.0.
0.1:8080/rest/items/JuanPC"}},{"widgetId":"default_0_0_1_2_3_4_5","type":"Group","label":"Kodi","icon":"sofa","linkedPage":{"id":"0005","title":"Kodi","icon":"sofa","link":"http://127
.0.0.1:8080/rest/sitemaps/default/0005","leaf":"true"}},{"widgetId":"default_0_0_1_2_3_4_5_6","type":"Group","label":"Astro","icon":"sun","linkedPage":{"id":"0006","title":"Astro","ic
on":"sun","link":"http://127.0.0.1:8080/rest/sitemaps/default/0006","leaf":"false"}},{"widgetId":"default_0_0_1_2_3_4_5_6_7","type":"Group","label":"Nodos","icon":"house","item":{"typ
e":"GroupItem","name":"Nodos","state":"Undefined","link":"http://127.0.0.1:8080/rest/items/Nodos"},"linkedPage":{"id":"0007","title":"Nodos","icon":"house","link":"http://127.0.0.1:80
80/rest/sitemaps/default/0007","leaf":"false"}},{"widgetId":"default_0_0_1_2_3_4_5_6_7_8","type":"Text","label":"Consumo [608.0 W]","icon":"energy","item":{"type":"NumberItem","name":
"Consumo_Entrada","state":"608","link":"http://127.0.0.1:8080/rest/items/Consumo_Entrada"}}]},{"widgetId":"default_1","type":"Frame","label":"","icon":"frame","widget":[{"widgetId":"d
efault_1_0","type":"Group","label":"Terraza","icon":"terrace","item":{"type":"GroupItem","name":"Terraza","state":"Undefined","link":"http://127.0.0.1:8080/rest/items/Terraza"},"linke
dPage":{"id":"0100","title":"Terraza","icon":"terrace","link":"http://127.0.0.1:8080/rest/sitemaps/default/0100","leaf":"false"}},{"widgetId":"default_1_0_1","type":"Group","label":"H
abitacion Ocio","icon":"firstfloor","item":{"type":"GroupItem","name":"Habitacion_Ocio","state":"Undefined","link":"http://127.0.0.1:8080/rest/items/Habitacion_Ocio"},"linkedPage":{"i
d":"0101","title":"Habitacion Ocio","icon":"firstfloor","link":"http://127.0.0.1:8080/rest/sitemaps/default/0101","leaf":"false"}},{"widgetId":"default_1_0_1_2","type":"Group","label"
:"Habitacion Dormir","icon":"groundfloor","item":{"type":"GroupItem","name":"Habitacion_Dormir","state":"Undefined","link":"http://127.0.0.1:8080/rest/items/Habitacion_Dormir"},"linke
dPage":{"id":"0102","title":"Habitacion Dormir","icon":"groundfloor","link":"http://127.0.0.1:8080/rest/sitemaps/default/0102","leaf":"true"}},{"widgetId":"default_1_0_1_2_3","type":"
Group","label":"Entrada","icon":"groundfloor","item":{"type":"GroupItem","name":"Entrada","state":"Undefined","link":"http://127.0.0.1:8080/rest/items/Entrada"},"linkedPage":{"id":"01
03","title":"Entrada","icon":"groundfloor","link":"http://127.0.0.1:8080/rest/sitemaps/default/0103","leaf":"true"}},{"widgetId":"default_1_0_1_2_3_4","type":"Group","label":"Nodo 3 -
 UNO","icon":"terrace","item":{"type":"GroupItem","name":"Nodo_3","state":"Undefined","link":"http://127.0.0.1:8080/rest/items/Nodo_3"},"linkedPage":{"id":"0104","title":"Nodo 3 - UNO
","icon":"terrace","link":"http://127.0.0.1:8080/rest/sitemaps/default/0104","leaf":"true"}},{"widgetId":"default_1_0_1_2_3_4_5","type":"Group","label":"Nodo 4","icon":"terrace","item
":{"type":"GroupItem","name":"Nodo_4","state":"Undefined","link":"http://127.0.0.1:8080/rest/items/Nodo_4"},"linkedPage":{"id":"0105","title":"Nodo 4","icon":"terrace","link":"http://
127.0.0.1:8080/rest/sitemaps/default/0105","leaf":"true"}}]},{"widgetId":"default_2","type":"Frame","label":"Fecha","icon":"frame","widget":[{"widgetId":"default_2_0","type":"Group","
label":"Luces","icon":"slider","item":{"type":"GroupItem","name":"Luces","state":"Undefined","link":"http://127.0.0.1:8080/rest/items/Luces"},"linkedPage":{"id":"0200","title":"Luces"
,"icon":"slider","link":"http://127.0.0.1:8080/rest/sitemaps/default/0200","leaf":"true"}},{"widgetId":"default_2_0_1","type":"Group","label":"Metereologia","icon":"sun","item":{"type
":"GroupItem","name":"Metereologia","state":"Undefined","link":"http://127.0.0.1:8080/rest/items/Metereologia"},"linkedPage":{"id":"0201","title":"Metereologia","icon":"sun","link":"h
ttp://127.0.0.1:8080/rest/sitemaps/default/0201","leaf":"false"}},{"widgetId":"default_2_0_1_2","type":"Group","label":"Temperaturas Medias  [26.0 ^`C]","icon":"temperature","item":{"
type":"GroupItem","name":"Temperaturas_Medias","state":"26.0","link":"http://127.0.0.1:8080/rest/items/Temperaturas_Medias"},"linkedPage":{"id":"0202","title":"Temperaturas Medias  [2
6.0 ^`C]","icon":"temperature","link":"http://127.0.0.1:8080/rest/sitemaps/default/0202","leaf":"true"}}]},{"widgetId":"default_3","type":"Frame","label":"Salud de los Nodos","icon":"
frame","widget":[{"widgetId":"default_3_0","type":"Group","label":"Debug","icon":"keyring","item":{"type":"GroupItem","name":"Debug","state":"Undefined","link":"http://127.0.0.1:8080/
rest/items/Debug"},"linkedPage":{"id":"0300","title":"Debug","icon":"keyring","link":"http://127.0.0.1:8080/rest/sitemaps/default/0300","leaf":"false"}},{"widgetId":"default_3_0_1","t
ype":"Group","label":"Timestamp","icon":"clock","item":{"type":"GroupItem","name":"Timestamp","state":"Undefined","link":"http://127.0.0.1:8080/rest/items/Timestamp"},"linkedPage":{"i
d":"0301","title":"Timestamp","icon":"clock","link":"http://127.0.0.1:8080/rest/sitemaps/default/0301","leaf":"true"}},{"widgetId":"default_3_0_1_2","type":"Text","label":"Salud Ocio
[255]","icon":"keyring","item":{"type":"NumberItem","name":"Salud_Ocio","state":"255.0","link":"http://127.0.0.1:8080/rest/items/Salud_Ocio"}},{"widgetId":"default_3_0_1_2_3","type":"
Text","label":"Salud Dormir [255]","icon":"keyring","item":{"type":"NumberItem","name":"Salud_Dormir","state":"255.0","link":"http://127.0.0.1:8080/rest/items/Salud_Dormir"}},{"widget
Id":"default_3_0_1_2_3_4","type":"Text","label":"Salud Entrada [25]","icon":"keyring","item":{"type":"NumberItem","name":"Salud_Entrada","state":"25.0","link":"http://127.0.0.1:8080/r
est/items/Salud_Entrada"}},{"widgetId":"default_3_0_1_2_3_4_5","type":"Text","label":"Salud Nodo_3 [231]","icon":"keyring","item":{"type":"NumberItem","name":"Salud_Nodo_3","state":"2
31.0","link":"http://127.0.0.1:8080/rest/items/Salud_Nodo_3"}},{"widgetId":"default_3_0_1_2_3_4_5_6","type":"Text","label":"Salud Nodo_4 [25]","icon":"keyring","item":{"type":"NumberI
tem","name":"Salud_Nodo_4","state":"25.0","link":"http://127.0.0.1:8080/rest/items/Salud_Nodo_4"}}]},{"widgetId":"default_4","type":"Frame","label":"","icon":"frame","widget":{"widget
Id":"default_4_0","type":"Group","label":"Webcam","icon":"video","linkedPage":{"id":"0400","title":"Webcam","icon":"video","link":"http://127.0.0.1:8080/rest/sitemaps/default/0400","l
eaf":"true"}}}]}]
20:36:31 T:1351611424   ERROR: Traceback (most recent call last):
20:36:31 T:1351611424   ERROR:   File "/home/osmc/.kodi/addons/script.module.openhab/addon.py", line 147, in <module>
20:36:31 T:1351611424   ERROR:     listing = createListingSite(siteMap)
20:36:31 T:1351611424   ERROR:   File "/home/osmc/.kodi/addons/script.module.openhab/addon.py", line 84, in createListingSite
20:36:31 T:1351611424   ERROR:     tmp_floor = Floor(floor['label'],floor['item']['link'], floor['linkedPage']['id'], floor['linkedPage']['leaf'])
20:36:31 T:1351611424   ERROR: KeyError: 'item'
20:36:31 T:1351611424  NOTICE: KeyError
20:36:31 T:1351611424  NOTICE: [openHab] ERROR: Exception Location: [Main Menu] Type:[KeyError] Exception:['item']

**Comment by enishoca** [comment]
Mike Hinton  
4:04 PM (2 hours ago)

Just tried 1.0.2 Windows 8.1

Debug part

10:28:01 T:2488   DEBUG: Activating window ID: 10001
10:28:01 T:2488   DEBUG: ------ Window Deinit (Home.xml) ------
10:28:01 T:2488   DEBUG: ------ Window Init (MyPrograms.xml) ------
10:28:01 T:2488   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/executable/)
10:28:01 T:2488   DEBUG:   ParentPath = [addons://sources/executable/]
10:28:01 T:4036  NOTICE: Thread BackgroundLoader start, auto delete: false
10:28:01 T:4036   DEBUG: Thread BackgroundLoader 4036 terminating
10:28:01 T:2504   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.axel.downloader\icon.png
10:28:03 T:2488   DEBUG: CApplication::ProcessMouse: trying mouse action leftclick
10:28:03 T:2488   DEBUG: CGUIMediaWindow::GetDirectory (plugin://script.module.openhab/)
10:28:03 T:2488   DEBUG:   ParentPath = [addons://sources/executable/]
10:28:03 T:2504   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin openhHab for Kodi('plugin://script.module.openhab/','3','')
10:28:03 T:2504   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the openhHab for Kodi (id=15) plugin...
10:28:03 T:6604  NOTICE: Thread LanguageInvoker start, auto delete: false
10:28:03 T:6604    INFO: initializing python engine.
10:28:03 T:6604   DEBUG: CPythonInvoker(15, C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab\addon.py): start processing
10:28:03 T:6604  NOTICE: -->Python Interpreter Initialized<--
10:28:03 T:6604   DEBUG: CPythonInvoker(15, C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab\addon.py): the source file to load is "C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab\addon.py"
10:28:03 T:6604   DEBUG: CPythonInvoker(15, C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab\addon.py): setting the Python path to C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab;C:\Program Files\Kodi\system\python\DLLs;C:\Program Files\Kodi\system\python\Lib;C:\Program Files\Kodi\python27.zip;C:\Program Files\Kodi\system\python\lib\plat-win;C:\Program Files\Kodi\system\python\lib\lib-tk;C:\Program Files\Kodi;C:\Program Files\Kodi\system\python;C:\Program Files\Kodi\system\python\lib\site-packages
10:28:03 T:6604   DEBUG: CPythonInvoker(15, C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab\addon.py): entering source directory C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab
10:28:03 T:6604   DEBUG: CPythonInvoker(15, C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab\addon.py): instantiating addon using automatically obtained id of "script.module.openhab" dependent on version 2.19.0 of the xbmc.python api
10:28:03 T:2488   DEBUG: ------ Window Init (DialogBusy.xml) ------
10:28:04 T:6604  NOTICE: [openHab] Starting
10:28:04 T:6604  NOTICE: [openHab] DEBUG: Debug Flag is true
10:28:04 T:6604  NOTICE: [openHab] Initializing - Main Menu
10:28:04 T:6604  NOTICE: [openHab] DEBUG: getJsonSiteMap url : [http://127.0.0.1:8080/rest/sitemaps/ArduinoDemo/Home?type=json]
10:28:04 T:6604  NOTICE: [openHab] DEBUG: getJson json_string : [{"id":"Home","title":"Home","link":"http://127.0.0.1:8080/rest/sitemaps/ArduinoDemo/Home","leaf":"true","widget":[{"widgetId":"Home_0","type":"Frame","label":"Ardunio 1","icon":"frame","widget":[{"widgetId":"Home_0_0","type":"Text","label":"Arduino_1 Online [OFF]","icon":"network-off","item":{"type":"SwitchItem","name":"Arduino_1_Up","state":"OFF","link":"http://127.0.0.1:8080/rest/items/Arduino_1_Up"}},{"widgetId":"Home_0_0_1","type":"Group","label":"Arduino_1","icon":"bath","item":{"type":"GroupItem","name":"Arduino_1","state":"Undefined","link":"http://127.0.0.1:8080/rest/items/Arduino_1"},"linkedPage":{"id":"0001","title":"Arduino_1","icon":"bath","link":"http://127.0.0.1:8080/rest/sitemaps/ArduinoDemo/0001","leaf":"false"}},{"widgetId":"Home_0_0_1_2","type":"Text","label":"Analog outputs - adjustable","icon":"settings","linkedPage":{"id":"0002","title":"Analog outputs - adjustable","icon":"settings","link":"http://127.0.0.1:8080/rest/sitemaps/ArduinoDemo/0002","leaf":"true"}}]},{"widgetId":"Home_1","type":"Frame","label":"Internet","icon":"frame","widget":{"widgetId":"Home_1_0","type":"Text","label":"Internet","icon":"network","linkedPage":{"id":"0100","title":"Internet","icon":"network","link":"http://127.0.0.1:8080/rest/sitemaps/ArduinoDemo/0100","leaf":"false"}}}]}]
10:28:04 T:6604   ERROR: Traceback (most recent call last):
10:28:04 T:6604   ERROR:   File "C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab\addon.py", line 147, in <module>
10:28:04 T:6604   ERROR:     listing = createListingSite(siteMap)
10:28:04 T:6604   ERROR:   File "C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab\addon.py", line 84, in createListingSite
10:28:04 T:6604   ERROR:     tmp_floor = Floor(floor['label'],floor['item']['link'], floor['linkedPage']['id'], floor['linkedPage']['leaf'])
10:28:04 T:6604   ERROR: KeyError: 'linkedPage'
10:28:04 T:6604  NOTICE: KeyError
10:28:04 T:6604  NOTICE: [openHab] ERROR: Exception Location: [Main Menu] Type:[KeyError] Exception:['linkedPage']
10:28:04 T:6604   DEBUG: LocalizeStrings: no strings.po file exist at C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab\resources\language\English, fallback to strings.xml
10:28:04 T:2488   DEBUG: ------ Window Init (DialogOK.xml) ------
10:28:08 T:2488   DEBUG: CApplication::ProcessMouse: trying mouse action leftclick
10:28:08 T:2488   DEBUG: ------ Window Deinit (DialogOK.xml) ------
10:28:08 T:6604    INFO: CPythonInvoker(15, C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab\addon.py): script successfully run
10:28:08 T:2488   DEBUG: CPythonInvoker(15, C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.openhab\addon.py): script termination took 0ms
10:28:08 T:6604    INFO: Python script interrupted by user
10:28:08 T:6604   DEBUG: Thread LanguageInvoker 6604 terminating
10:28:08 T:2504   DEBUG:  XFILE::CPluginDirectory::WaitOnScriptResult - plugin exited prematurely - terminating
10:28:08 T:2488   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://script.module.openhab/
10:28:08 T:2488   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.module.openhab/) failed
10:28:08 T:2488   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/executable/)
10:28:08 T:2488   DEBUG:   ParentPath = []
10:28:08 T:6940  NOTICE: Thread BackgroundLoader start, auto delete: false
10:28:09 T:2488   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
10:28:09 T:2504   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url C:\Users\Mike\AppData\Roaming\Kodi\addons\script.module.axel.downloader\icon.png
10:28:09 T:6940   DEBUG: Thread BackgroundLoader 6940 terminating

**Comment by enishoca** [comment]
Manuel Carlos Rodriguez  
4:36 PM (2 hours ago)

Attached my info.

22:28:34 T:1768895552  NOTICE: [openHab] Starting
22:28:34 T:1768895552  NOTICE: [openHab] DEBUG: Debug Flag is true
22:28:34 T:1768895552  NOTICE: [openHab] Initializing - Main Menu
22:28:34 T:1768895552  NOTICE: [openHab] DEBUG: getJsonSiteMap url : [http://127.0.0.1:8080/rest/sitemaps/Lillo/Lillo?type=json]
22:28:34 T:1768895552  NOTICE: [openHab] DEBUG: getJson json_string : [{"id":"Lillo","title":"Main Menu","link":"http://127.0.0.1:8080/rest/sitemaps/Lillo/Lillo","leaf":"false","widget":[{"widgetId":"Lillo_0","type":"Switch","label":"Enchufe","icon":"socket-off","item":{"type":"SwitchItem","name":"Enchufe1","state":"OFF","link":"http://127.0.0.1:8080/rest/items/Enchufe1"}},{"widgetId":"Lillo_1","type":"Switch","label":"Interruptor","icon":"switch-off","item":{"type":"SwitchItem","name":"Interruptor1","state":"OFF","link":"http://127.0.0.1:8080/rest/items/Interruptor1"}},{"widgetId":"Lillo_2","type":"Text","label":"MQTT [-]","icon":"bluetooth","item":{"type":"NumberItem","name":"testmqtt","state":"Uninitialized","link":"http://127.0.0.1:8080/rest/items/testmqtt"}},{"widgetId":"Lillo_3","type":"Text","label":"Temperatura [25.0 ºC]","icon":"temperature","item":{"type":"NumberItem","name":"Temperatura","state":"25.00","link":"http://127.0.0.1:8080/rest/items/Temperatura"}},{"widgetId":"Lillo_4","type":"Text","label":"DAFDSF [-]","icon":"switch","item":{"type":"StringItem","name":"test2mqtt","state":"Uninitialized","link":"http://127.0.0.1:8080/rest/items/test2mqtt"}},{"widgetId":"Lillo_5","type":"Group","label":"dfasf","icon":"group","linkedPage":{"id":"05","title":"dfasf","icon":"group","link":"http://127.0.0.1:8080/rest/sitemaps/Lillo/05","leaf":"true"}},{"widgetId":"Lillo_6","type":"Group","label":"XBMC","icon":"group","linkedPage":{"id":"06","title":"XBMC","icon":"group","link":"http://127.0.0.1:8080/rest/sitemaps/Lillo/06","leaf":"true"}}]}]
22:28:34 T:1768895552   ERROR: Traceback (most recent call last):
22:28:34 T:1768895552   ERROR:   File "/storage/.kodi/addons/script.module.openhab/addon.py", line 147, in <module>
22:28:34 T:1768895552   ERROR:     listing = createListingSite(siteMap)
22:28:34 T:1768895552   ERROR:   File "/storage/.kodi/addons/script.module.openhab/addon.py", line 81, in createListingSite
22:28:34 T:1768895552   ERROR:     widgets2.append(w['widget'])
22:28:34 T:1768895552   ERROR: KeyError: 'widget'
22:28:34 T:1768895552  NOTICE: KeyError
22:28:34 T:1768895552  NOTICE: [openHab] ERROR: Exception Location: [Main Menu] Type:[KeyError] Exception:['widget']
22:28:36 T:1970033184   ERROR: GetDirectory - Error getting plugin://script.module.openhab/
22:28:36 T:1970033184   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.module.openhab/) failed
22:28:36 T:1768895552  NOTICE: Thread BackgroundLoader start, auto delete: false

HTH

**Comment by martenjacobs** [comment]
I get this issue as well:

```
20:44:22 T:140187023218432  NOTICE: Thread LanguageInvoker start, auto delete: false
20:44:22 T:140187103348480  NOTICE: Thread JobWorker start, auto delete: true
20:44:22 T:140188448053120   ERROR: Control 50 in window 10001 has been asked to focus, but it can't
20:44:22 T:140187023218432  NOTICE: -->Python Interpreter Initialized<--
20:44:22 T:140187023218432  NOTICE: [openHab] Starting
20:44:22 T:140187023218432  NOTICE: [openHab] Initializing - Main Menu
20:44:22 T:140187023218432   ERROR: Traceback (most recent call last):
20:44:22 T:140187023218432   ERROR:   File "/storage/.kodi/addons/script.module.openhab/addon.py", line 147, in <module>
20:44:22 T:140187023218432   ERROR:     listing = createListingSite(siteMap)
20:44:22 T:140187023218432   ERROR:   File "/storage/.kodi/addons/script.module.openhab/addon.py", line 84, in createListingSite
20:44:22 T:140187023218432   ERROR:     tmp_floor = Floor(floor['label'],floor['item']['link'], floor['linkedPage']['id'], floor['linkedPage']['leaf'])
20:44:22 T:140187023218432   ERROR: TypeError: string indices must be integers
20:44:22 T:140187023218432  NOTICE: TypeError
20:44:22 T:140187023218432  NOTICE: [openHab] ERROR: Exception Location: [Main Menu] Type:[TypeError] Exception:[string indices must be integers]
```

The add-on does not function at all for me at the moment, showing only 'An error occurred' on screen.
